name: destini
description: Modular Flutter Choose Your Story Game

version: 1.0.0+1



environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  rflutter_alert: ^2.0.4
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - images/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logo.png"

